project_name: probe
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./main.go
    binary: probe
    goos: [ 'linux', 'darwin', 'windows' ]
    goarch: [ '386', 'amd64', 'arm64' ]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.version={{.Version}}"

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - package_name: probe
    vendor: abhimanyu003
    homepage: "https://github.com/abhimanyu003/probe/"
    maintainer: "Abhimanyu Sharma <abhimanyusharma003@gmail.com>"
    description: "Simplified Integration Testing Using YAML and JQ."
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin

brews:
  - tap:
      owner: abhimanyu003
      name: homebrew-tap
    folder: Formula
    name: probe
    homepage: "https://github.com/abhimanyu003/probe"
    description: "Simplified Integration Testing Using YAML and JQ."
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: abhimanyu003
      email: abhimanyusharma003@gmail.com
    install: |-
      bin.install "probe"
    test: |
      system "#{bin}/probe -v"

scoop:
  bucket:
    owner: abhimanyu003
    name: scoop-bucket
  commit_author:
    name: "Abhimanyu Sharma"
    email: abhimanyusharma003@gmail.com
  homepage: "https://github.com/abhimanyu003/sttr"
  description: "Simplified Integration Testing Using YAML and JQ."
  license: MIT

snapcrafts:
  - id: probe
    name: go-probe
    publish: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    summary: Simplified Integration Testing Using YAML and JQ.
    description: |
      Simplified Integration Testing Using YAML and JQ.
    grade: stable
    confinement: strict
    license: MIT
    base: core20
    apps:
      probe:
        command: probe
        plugs: [ "home", "network" ]
        aliases: [ "probe" ]

aurs:
  - name: probe-bin
    homepage: "https://github.com/abhimanyu003/probe"
    description: "Simplified Integration Testing Using YAML and JQ."
    maintainers:
      - 'Abhimanyu Sharma <abhimanyusharma003@gmail.com>'
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/probe-bin.git'
    commit_author:
      name: Abhimanyu Sharma
      email: abhimanyusharma003@gmail.com
